bin = []
bench = []
test = []
example = []

[package]
name = "adapter"
edition = "2021"
version = "0.0.1"
autobins = true
autoexamples = true
autotests = true
autobenches = true

[dependencies]
diesel_migrations = "2.1.0"

[dependencies.async-trait]
version = "0.1.77"

[dependencies.deadpool-diesel]
version = "0.5.0"
features = ["postgres", "serde"]

[dependencies.diesel]
version = "2.1.4"
features = ["postgres", "postgres_backend", "uuid"]

[dependencies.rust_core]
path = "../core"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.testcontainers-modules]
version = "0.3.4"
features = ["postgres"]

[dependencies.tokio]
version = "1.36.0"
features = ["full"]

[dependencies.anyhow]
version = "1.0.80"